In [1]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv('result_trader_bot/log (2).txt', delimiter='\t')
df

     [25/09/2023 22:22:43]Starting Bot ...
0       [25/09/2023 22:22:43]News Time? No
1       [25/09/2023 22:23:13]News Time? No
2       [25/09/2023 22:23:43]News Time? No
3       [25/09/2023 22:24:13]News Time? No
4       [25/09/2023 22:24:43]News Time? No
...                                    ...
9255    [03/10/2023 14:21:19]News Time? No
9256    [03/10/2023 14:21:49]News Time? No
9257    [03/10/2023 14:22:20]News Time? No
9258    [03/10/2023 14:22:50]News Time? No
9259    [03/10/2023 14:23:20]News Time? No

[9260 rows x 1 columns]

[25/09/2023 22:22:43]Starting Bot ...    [25/09/2023 22:22:43]News Time? No
Name: 0, dtype: object

In [7]:
filtered_df = df[df['Type'].isin(['buy stop', 'sell stop'])]
filtered_df = filtered_df.drop(columns=['Order', 'Unnamed: 10'])
filtered_df

,Open Time,Symbol,Type,Volume,Price,S / L,T / P,Time,State,Comment
39,2023.09.20 14:55:46,GBPCAD,buy stop,0.32 / 0.32,1.6616,1.6574,1.6688,2023.09.20 15:26:34,filled,ECB McCaul Speak
70,2023.09.21 13:56:03,GBPJPY,buy stop,0.19 / 0,182.37,181.5720,183.5890,2023.09.21 14:05:28,canceled,BoE Interest Rat
85,2023.09.21 16:55:41,AUDUSD,buy stop,0.23 / 0,0.6462,0.6419,0.6531,2023.09.21 17:20:17,canceled,Existing Home Sa
87,2023.09.21 16:55:42,GBPUSD,buy stop,0.18 / 0,1.2365,1.2309,1.2458,2023.09.21 17:32:19,canceled,Existing Home Sa
89,2023.09.21 17:25:57,USDJPY,buy stop,0.28 / 0,147.659,147.1290,148.5200,2023.09.21 22:23:34,canceled,Natural Gas Stor
97,2023.09.21 17:35:34,EURGBP,sell stop,0.37 / 0,0.8649,0.8671,0.8610,2023.09.21 22:23:21,canceled,ECB's Schnabel S
112,2023.09.22 09:25:36,EURAUD,buy stop,0.19 / 0.19,1.6582,1.6501,1.6704,2023.09.22 09:34:33,filled,BoJ Press Confer
118,2023.09.22 10:25:18,EURNZD,buy stop,0.15 / 0,1.7933,1.7819,1.8118,2023.09.22 11:46:59,canceled,HCOB Germany Com

GBPCAD
timeframe: 0.5
country=Euro Zone, news=ECB McCaul Speaks

GBPCAD multiplyer = 0.001
function_over_price(mean Max open) = 127.6*2 = 255.2
function_over_price(mean Min open) = 153.8*2 = 307.6

profit = 720.2

def price_calc(open_, pip, multiplier)
price = round((pip*multiplier)+ open_, ndigits=4)

entry_point = price_calc(open_, function_over_price(price_mean), multiplier)
(mean Max open * multiplyer) + open

open = 1.66097

In [29]:
round((255.2*0.001)+ 1.66097, ndigits=4)

1.6865

In [30]:
round(1.66097 - ( 307.6*0.001), ndigits=4)

1.6302

In [19]:
df[35:41]

,Open Time,Order,Symbol,Type,Volume,Price,S / L,T / P,Time,State,Unnamed: 10,Comment
35,2023.09.20 11:55:20,180152891,EURNZD,buy limit,0.2 / 0.2,1.7948,1.7865,1.8083,2023.09.20 13:41:30,filled,NaN,Construction Out
36,2023.09.20 11:55:20,180152892,EURNZD,sell limit,0.19 / 0,1.8047,1.8135,1.7912,2023.09.21 07:38:22,canceled,NaN,Construction Out
37,2023.09.20 14:55:45,180192204,EURCHF,buy limit,0.18 / 0,0.9556,0.9506,0.9650,2023.09.21 07:38:17,canceled,NaN,ECB McCaul Speak
38,2023.09.20 14:55:45,180192206,EURCHF,sell limit,0.15 / 0,0.9634,0.9695,0.9540,2023.09.21 07:38:18,canceled,NaN,ECB McCaul Speak
39,2023.09.20 14:55:46,180192207,GBPCAD,buy stop,0.32 / 0.32,1.6616,1.6574,1.6688,2023.09.20 15:26:34,filled,NaN,ECB McCaul Speak
40,2023.09.20 14:55:46,180192208,GBPCAD,sell limit,0.29 / 0,1.6672,1.6719,1.6600,2023.09.21 07:38:22,canceled,NaN,ECB McCaul Speak